[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.1.0"
  JEKYLL_ENV = "production"
  NODE_VERSION = "16"

[[plugins]]
  package = "netlify-plugin-jekyll-cache"

[context.production]
  environment = { JEKYLL_ENV = "production" }

[context.deploy-preview]
  command = "bundle exec jekyll build --future" 